Universidad Galileo  
Maestría en Data Science  
Ciencia de datos en Python  
Sección U  


   # **INVESTIGACIÓN Y EJERCICIOS FINALES NOTEBOOKS 7 y 8**


<p style="text-align: right;">
Henry Giovanni<br/>
Barrientos García<br/>
21001538<br/>
Guatemala, 14 de abril de 2021<br/>
</p>

   # INVESTIGACIÓN

---

## DIFERENCIAS ENTRE numpy.array y numpy.matrix

numpy.array y numpy.matrix son dos funciones de la librería numpy especializada en análisis de datos del lenguaje de programación de Python, básicamente ambas se utilizan para la creación de arrays o matrices de datos, a continuación se provee un resumen mas adecuado.

## numpy.array
---

Estos son un tipo especial de estructura de datos. Básicamente son arrays multidimensionales o listas de tamaño fijo con elementos de similar valor. Los arrays de numpy, se han convertido en un buen sustituto de las listas en Python, esto debido a lo optimizado de su funcionamiento, a la velocidad con que se realizan sus operaciones y el poco espacio que utilizan en memoria.

A continuación un ejemplo de la visualización de un array de distintas dimensiones:

<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmiro.medium.com%2Fmax%2F817%2F0*y04Nh3L0aSwyGaby.png&f=1&nofb=1" width="50%" height="50%">

La forma típica de definir un numpy.array, con los atributos más comunes, es como se muestra a continuación (ésos valores de inicialización, son los que se toman por defecto):
``` python
numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
```

Aunque existen más parámetros, en la línea anterior se muestran los más comunes y a continuación se da una breve descripción de cada uno:
- **object:** Especifica el objeto a partir del cual se quiere construir un numpy.array
- **dtype:** Especifica el tipo de dato para los elementos del array, es útil cuando el array se construye a partir de otras funciones "constructoras" de numpy.
- **copy:** Especifica si se desea que el nuevo array va a ser una copia de la fuente o no.
- **order:** Especifica el diseño de la memoria de la matriz.
- **subok:** Determina si desea una subclase o una matriz de tipo de clase base.
- **ndmin:** Indica las dimensiones deseadas del array resultante.

#### **Funciones de numpy.array**
Los arrays tienen varias funciones/atributos, pero hay unos mas importantes/usados que otros, a continuación se detallan los más comunes:
- **size:** Devuelve el número total de elementos en el array.
- **shape:** Devuelve "la forma" del array, retorna algo como (xfilas, ycolumnas, zprofundidad).
- **dim:** Retorna el rango de la matriz, es decir, el número de dimensiones.
- **dtype:** Muestra el tipo de dato de los elementos de la matriz.
- **itemsize:** Retorna el tamaño, en bytes, de cada elemento del array.
- **nbytes:** Retorna el tamaño total del array, en bytes.

#### Documentación numpy.array
La documentación completa de la función se puede encontrar acá: [numpy.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html)

## numpy.matrix
___

La función matrix de la librería numpy, es una subclase de ndarray. Provee la posibilidad de crear matrices a partir de cadenas de texto u objetos que implementen la interfaz array, la matriz resultante es específicamente una de dos dimensiones (2D). El resultado es una matriz especializada 2D, la cual provee a programadores y científicos de datos varias operaciones que son específicas de matrices 2D. Un dato importante es que numpy.matrix define y trabaja con matrices de 2 dimensiones, no importando si estas son cuadradas o no. 

**Broadcasting**  
Es la capacidad que tiene Python de replicar un vector tantas veces como sea necesario para que "tengan la forma" de otra matriz con la que se quiere operar, es decir, a partir de un vector se crea una matriz transitoria a partir de la cual se ejecutarán operaciones elemento a elemento con otra matriz.Python "completa" la matriz forzando las operaciones en los ejes donde los datos no existen.  
Broadcasting no funciona en casos donde las dimensiones no son compatibles, por ejemplo para el caso anterior, broadcasting no hubiera funcionado si el vector tuviera 3 elementos y hubiera resultado en un error: *operands could not be broadcast together with shapes ...*

**Ventajas**
1. Ocupa menos espacio de memoria y brinda una mayor velocidad de ejecución en comparación con estructuras de datos similares de Python (listas y tuplas).
1. Permite la ejecución de funciones científicas específicas, como la suma acumulativa de elementos, el producto acumulativo, la transposición conjugada y la inversa multiplicativa, etc. Las listas o cadenas de Python no admiten estas características u operaciones.

Las matrices de numpy tienen, como ya dijimos 2 dimensiones, a continuación una imagen de su visualización:
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.stack.imgur.com%2FO5hBF.jpg&f=1&nofb=1">

A continuación veremos algunos de sus propiedades y funciones más importantes.
A continuación se muestra la definición típica de una matriz con numpy (los valores de inicialización, son los definidos por defecto):
``` python
numpy.matrix(data, dtype=None, copy=True)
```
Donde los parámetros del constructor se definen como de muestra a continuación:
- **data:** Los datos deben tener la forma de un array, ser un objeto que implemente la interfaz array o una cadena de elemetos numéricos separada por comas.
- **dtype:** Define el tipo de dato de la matriz retornada.
- **copy:** Indica si los datos se copian o si se construye una nueva vista.

#### Funciones de numpy.matrix

Como ya hemos dicho numpy.matrix, se especializa en matrices de dos dimensiones, y dado esto tiene operaciones que son específicas de matrices de estas dimensiones.

- **matrix.T:** Retorna la matriz transpuesta
- **matrix.H:** Retorna la matriz transpuesta conjugada
- **matrix.I:** Retorna la inversa multiplicativa
- **matrix.A:** Devuelve la matriz original como un objeto ndarray.
- **matrix.any():** Determina si alguno de los elementos de un eje dado es verdadero.
- **matrix.argmax():** Devuelve los índices de los valores máximos en un eje dado.
- **matrix.argmin():** Retorna los índices de los malores mínimos sobre el eje indicado.
- **matrix.cumprod():** Devuelve el producto acumulado de los elementos sobre el eje en la dimensión indicada.
- **matrix.cumsum():** Devuelve la suma acumulada de los elementos sobre el eje en la dimensión indicada.
- **matrix.diagonal():** Retorna los elementos de la diagonal de una matriz.
- **matrix.dot():**	Retorna el producto punto entre dos matrices.

#### Documentación de numpy.matrix

La documentación se puede encontrar en el siguiente enlace:[numpy.matrix](https://numpy.org/doc/stable/reference/generated/numpy.matrix.html)


**>>>EJEMPLOS DE CÓDIGO numpy.array<<<**
___

In [1]:
# Formas de crear un numpy.array
import numpy as np

array_f = np.ndarray(shape = (3, 3), dtype = bool)
print("Array creado con valores random y especificando un tipo de dato:\n", array_f)

array_s = np.array([[1, 2, 3], [9, 8, 7]])
print ("Array creado a partir de una lista:\n", array_s)

array_t = np.array((8, 9, 10))
print ("Array creado con una tupla:\n", array_t)

Array creado con valores random y especificando un tipo de dato:
 [[ True False  True]
 [False  True False]
 [ True False  True]]
Array creado a partir de una lista:
 [[1 2 3]
 [9 8 7]]
Array creado con una tupla:
 [ 8  9 10]


In [2]:

# Crear numpy.array
nparr = np.array([[1,2,3],[9,8,7],[10,20,30]])
print("nparr:\n",nparr)

print("Tipo de objeto:", type(nparr))

print("Forma:", nparr.shape)

print("No. dimensiones:", nparr.ndim)

print("Tamaño:", nparr.size)

print("Tipo de elemento:", nparr.dtype)

nparr:
 [[ 1  2  3]
 [ 9  8  7]
 [10 20 30]]
Tipo de objeto: <class 'numpy.ndarray'>
Forma: (3, 3)
No. dimensiones: 2
Tamaño: 9
Tipo de elemento: int32


In [3]:
# Constructores especiales de arrays

aones = np.ones((3, 3))
print ("Array con valores 1:\n", aones)

arrzeros = np.zeros((3, 3))
print ("Array con valores 0:\n", arrzeros)

arrcomp = np.full((3, 3), 1, dtype = 'complex')
print ("Array con elementos de tipo complejo:\n", arrcomp)

arrbuff = np.ndarray((2,), buffer=np.array([1,2,3]), dtype=int)
print ("Array especificando bufer:\n", arrbuff)

arrran = np.arange(15)
print ("Array con rango especificado:\n", arrran)

Array con valores 1:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array con valores 0:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array con elementos de tipo complejo:
 [[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]
Array especificando bufer:
 [1 2]
Array con rango especificado:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
# Trabjando con arrays de tres dimensiones
dimmm = np.array([
    [[ 0,  1,  2,  3],
    [ 4,  5,  6,  7],
    [ 8,  9, 10, 11]],
    [[12, 13, 14, 15],
    [16, 17, 18, 19],
    [20, 21, 22, 23]]
])
print("Array 3D:\n", dimmm)
print("Elemento en el indice (0,0,1): ", dimmm[0,0,1])
print("Elemento en el indice (1,2,3): ", dimmm[1,2,3])
# Al cambiar el valor en una posicion
dimmm[1,0,2] = 31
print("Array 3D luego del cambio:\n", dimmm)

Array 3D:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Elemento en el indice (0,0,1):  1
Elemento en el indice (1,2,3):  23
Array 3D luego del cambio:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 31 15]
  [16 17 18 19]
  [20 21 22 23]]]


**>>> EJEMPLOS DE CÓDIGO numpy.matrix <<<**
___

In [5]:
import numpy as np

test_mat = np.matrix('9 8 1; 0 5 10; 3 3 3')
print("Matriz :\n", test_mat)
print("Matriz transpuesta:\n", test_mat.getT())
print("Matriz transpuesta conjuda:\n", test_mat.getH())
print("Inversa multiplicativa de matriz:\n",test_mat.getI())

# tanto argmax, argmin, reciben el parametro axis, 0 indica operar sobre las filas
print("\nÍndices donde están los máximos:", test_mat.argmax(0))
print("Índices donde están los mínimos:", test_mat.argmin(0))
print("Producto acumulado de los elementos:\n", test_mat.cumprod(0))
print("Suma acumulada de los elementos:\n", test_mat.cumsum(0))

# A continuación operaciones especiales de matrices
print("\nDiagonal de la matriz:", test_mat.diagonal(0,0,1))
print("Producto punto de dos matrices (iguales):\n", test_mat.dot(2))

Matriz :
 [[ 9  8  1]
 [ 0  5 10]
 [ 3  3  3]]
Matriz transpuesta:
 [[ 9  0  3]
 [ 8  5  3]
 [ 1 10  3]]
Matriz transpuesta conjuda:
 [[ 9  0  3]
 [ 8  5  3]
 [ 1 10  3]]
Inversa multiplicativa de matriz:
 [[-0.16666667 -0.23333333  0.83333333]
 [ 0.33333333  0.26666667 -1.        ]
 [-0.16666667 -0.03333333  0.5       ]]

Índices donde están los máximos: [[0 0 1]]
Índices donde están los mínimos: [[1 2 0]]
Producto acumulado de los elementos:
 [[  9   8   1]
 [  0  40  10]
 [  0 120  30]]
Suma acumulada de los elementos:
 [[ 9  8  1]
 [ 9 13 11]
 [12 16 14]]

Diagonal de la matriz: [[9 5 3]]
Producto punto de dos matrices (iguales):
 [[18 16  2]
 [ 0 10 20]
 [ 6  6  6]]


## EJERCICIO NOTEBOOK 8

In [10]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1    
    return 1/(1 + np.exp(-x))

def af_relu(x):   # implement ReLU activation function
    return np.maximum(0, X)

def neural_network_test(X):
    H1_W = np.array([ [0.712, 0.355, 0.268], [0.112, 0.855, 0.468] ])
    OL_W = np.array([ [0.116], [0.329], [0.708] ])
    H1 = np.matmul(X, H1_W)
    H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
    OL = np.matmul(H1, OL_W)
#     print("Sigmud activation function:\n", sigmoid(OL))
    OL = af_relu(OL)  # convertir a valores en el intervalo de 0 a 1
    print("ReLU activation function:\n", OL)

X = np.array([[0.1, 2],
              [0.3, 0.45],
              [5,   9],
              [12,  6],
              [7,   5],
              [0.3, 0.8],
              [12,  5],
              [100, 200],
              [7,   8],
              [300, 1500] ])
neural_network_test( X )

ReLU activation function:
 [[1.0e-01 2.0e+00]
 [3.0e-01 4.5e-01]
 [5.0e+00 9.0e+00]
 [1.2e+01 6.0e+00]
 [7.0e+00 5.0e+00]
 [3.0e-01 8.0e-01]
 [1.2e+01 5.0e+00]
 [1.0e+02 2.0e+02]
 [7.0e+00 8.0e+00]
 [3.0e+02 1.5e+03]]


In [11]:
def neural_network(X):
    H1_W = np.array([[0.25, -8],
                     [0.37, 14] ])
    OL_W = np.array([[4],[9]])
    H1 = np.matmul(X, H1_W)
    H1 = sigmoid(H1)  # convertir a valores en el intervalo de 0 a 1
    OL = np.matmul(H1, OL_W)
#     print("Sigmud activation function:\n", sigmoid(OL))
    OL = af_relu(OL)  # convertir a valores en el intervalo de 0 a 1
    print("ReLU activation function:\n", OL)

X = np.array([[0.1, 2],
              [0.3, 0.45],
              [5,   9],
              [12,  6],
              [7,   5],
              [0.3, 0.8],
              [12,  5],
              [100, 200],
              [7,   8],
              [300, 1500] ])
neural_network( X )

ReLU activation function:
 [[1.0e-01 2.0e+00]
 [3.0e-01 4.5e-01]
 [5.0e+00 9.0e+00]
 [1.2e+01 6.0e+00]
 [7.0e+00 5.0e+00]
 [3.0e-01 8.0e-01]
 [1.2e+01 5.0e+00]
 [1.0e+02 2.0e+02]
 [7.0e+00 8.0e+00]
 [3.0e+02 1.5e+03]]
